#!/usr/bin/env bash

# shellcheck disable=SC1091
source "$HOME/.config/theme/palette.sh"

options=(
  active_color="$BORDER_ACTIVE"
  inactive_color="$BORDER_INACTIVE"
  width=5.0
  hidpi=on
)

borders "${options[@]}"
