# chezmoi:template:left-delimiter="# {{" right-delimiter=}}

[".config/nushell/scripts/external/bash-env-nushell"]
type = "git-repo"
url = "git@github.com:tesujimath/bash-env-nushell.git"
refreshPeriod = "168h"

[".config/nushell/scripts/external/bash-env-nushell"."pull"]
args = ["--rebase", "--autostash"]

# {{ if eq .chezmoi.os "darwin" -}}

[".config/sketchybar/external/sketchybar-app-font"]
type = "git-repo"
url = "https://github.com/kvndrsslr/sketchybar-app-font.git"
refreshPeriod = "168h"

[".config/sketchybar/external/sketchybar-app-font"."pull"]
args = ["--rebase", "--autostash"]

[".config/ghostty/shaders/cursors"]
type = "git-repo"
url = "https://github.com/sahaj-b/ghostty-cursor-shaders.git"
refreshPeriod = "168h"

[".config/ghostty/shaders/cursors"."pull"]
args = ["--rebase", "--autostash"]

# {{- end -}}

# {{ if eq .chezmoi.hostname "box" -}}

# {{- end -}}
