gui:
  showBottomLine: false
  expandFocusedSidePanel: true
os:
  edit: "hx {{filename}}"
  editAtLine: "hx -- {{filename}}:{{line}}"
  editAtLineAndWait: "hx -- {{filename}}:{{line}}"
  openDirInEditor: "hx -- {{dir}}"
notARepository: "quit"
promptToReturnFromSubprocess: false
