git:
  branchPrefix: "tifan/"
  paging:
    colorArg: always
    pager: delta --paging=never # other configs in gitconfig
gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 99
  border: "single"
  showPanelJumps: false
  showFileTree: false
  sidePanelWidth: 0.22
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - "#282828"
os:
  editPreset: "zed"
notARepository: "quit"
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-r>"
    context: global
    command: "gh repo view --web"
