git:
  paging:
    externalDiffCommand: difft --color=always --display=side-by-side --syntax-highlight=off
gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 99
  border: "single"
  showPanelJumps: false
  showFileTree: false
  sidePanelWidth: 0.22
  # showBottomLine: false
  theme:
    selectedLineBgColor:
      - "#282828"
os:
  editPreset: "vi"
notARepository: "quit"
promptToReturnFromSubprocess: false
customCommands:
  - key: "<c-r>"
    context: global
    command: "gh repo view --web"
