git:
  paging:
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=off
gui:
  showBottomLine: true
  expandFocusedSidePanel: true
  border: "single"
os:
  editPreset: "vscode"
notARepository: "quit"
promptToReturnFromSubprocess: false
