# https://github.com/helix-editor/helix/blob/master/runtime/themes/gruber-darker.toml
inherits = "gruber-darker"

"ui.statusline" = { fg = "fg0", bg = "bg1" }
"ui.statusline.normal" = { fg = "black", bg = "quartz", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "niagara0", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "black", bg = "fg0", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "fg3" }

"ui.bufferline" = { fg = "fg3", bg = "bg1" }
"ui.bufferline.active" = { fg = "fg0", bg = "bg1" }

"ui.virtual.ruler" = { bg = "bg1" }

"ui.virtual.whitespace" = "#595959"

"ui.virtual.jump-label" = { fg = "brown0", modifiers = ["bold"] }

"comment" = { fg = "gray" }
