# https://github.com/helix-editor/helix/blob/master/runtime/themes/gruber-darker.toml
inherits = "gruber-darker"

"ui.background" = {}

"ui.statusline" = { fg = "fg0", bg = "bg0" }
"ui.statusline.normal" = { fg = "black", bg = "quartz", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "black", bg = "niagara0", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "black", bg = "fg0", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "fg3" }

"ui.virtual.ruler" = { bg = "bg0" }
"ui.virtual.whitespace" = "bg8"

"comment" = { fg = "gray" }
