# default: https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/keymap.toml

"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Note:
# arrow.yazi and smart-enter.yazi are custom plugins that I manually installed
# therefore they are not managed by `ya pack` and are pushed to dotfiles git repo

# disable default keymaps
[[manager.prepend_keymap]]
on = ["<C-Enter>"]
run = ","
[[manager.prepend_keymap]]
on = ["t"]
run = ","

# https://yazi-rs.github.io/docs/tips#dropping-to-shell
[[manager.prepend_keymap]]
on = "<C-s>"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# https://yazi-rs.github.io/docs/tips#close-input-by-esc
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

# https://yazi-rs.github.io/docs/tips#navigation-wraparound
[[manager.prepend_keymap]]
on = "k"
run = "plugin arrow --args=-1"
[[manager.prepend_keymap]]
on = "j"
run = "plugin arrow --args=1"

# https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# force delete to trash with d
# { on = ["d"], run = "remove --force", desc = "Move the files to the trash" },

# open shell
# { on = ["<C-s>"], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
# ]
