"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
border_style = { fg = "gray" }
preview_hovered = {}
count_selected = { fg = "black", bg = "yellow", bold = true }
count_copied = { fg = "black", bg = "yellow", blink_rapid = true, bold = true }

[status]
separator_open = ""
separator_close = ""

[mode]
normal_main = { fg = "black", bg = "blue", bold = true }
normal_alt = { fg = "blue", bg = "reset" }
select_main = { fg = "black", bg = "yellow", bold = true }
select_alt = { fg = "yellow", bg = "reset" }
unset_main = { fg = "yellow", bg = "reset", bold = true }
unset_alt = { fg = "blue", bg = "reset" }
