#!/bin/sh

# core-utils
alias rm="rm -rf"
alias mv="mv -i"
alias cp="cp -ri"
alias mkdir="mkdir -p"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ping="ping -c 3"
alias dmesg="dmesg -H"
alias date="date '+%A, %B %d, %Y [%T]'"
alias df="df -h"
alias lsblk="lsblk -o NAME,FSTYPE,LABEL,SIZE,FSUSE%,FSAVAIL,MOUNTPOINT"
alias du="du -h"
alias du1="du --max-depth=1"

# needs nautilus/other file manager (open in current working dir)
alias .="nautilus -w . &"

# needs ncdu
alias ncdu="ncdu -re"

# arch linux specific
# alias makepkg="makepkg -fsri"

# pnpm
alias pn="pnpm"
alias npm="pnpm"
alias npx="pnpm dlx"

# yadm
alias ya="yadm"
alias yas="yadm status"
alias yal="yadm list -a"
alias yau="yadm add -u && yadm commit -m 'update' && yadm push"

# push Notes
alias obu="git -C ~/Documents/Notes add . && git -C ~/Documents/Notes commit -m 'update' && git -C ~/Documents/Notes push"

# update
alias up="clear && sudo dnf up -y && flatpak update --noninteractive && pnpm update -g --latest"

# exa (needs nerd-fonts)
alias ls="exa -lhF --group-directories-first --icons -s extension"
alias lsa="exa -lhFa --group-directories-first --icons -s extension"

# bat
alias cat="bat"
# use help [program] instead of [program] --help (this will colorize it)
help() {
  "$@" --help 2>&1 | bat --plain --language=help
}

# yt-dlp
yd() {
  # additional config is stored at ~/.config/yt-dlp/config

  if [[ "$1" == "" ]]; then
    echo "Usage: yd \"[url]\""
    return
  fi

  echo "Choose a video resolution, or audio only:"
  echo "1. 720p"
  echo "2. 1080p"
  echo "3. Audio only"
  echo "Enter your choice (1-3): "
  read -r choice

  case "$choice" in
    1) yt-dlp --format-sort "res:720,codec:avc:m4a" "$1" ;;
    2) yt-dlp --format-sort "res:1080,codec:avc:m4a" "$1" ;;
    3) yt-dlp -f 140 "$1" ;;
    *) echo "Invalid choice." ;;
  esac

  echo "\nDownloaded and stored at ~/Media/Videos/YouTube"
}

# gnome DE
edit() {
  [ -f "$1" ] && gnome-text-editor -- "$1" &
}
