#!/bin/bash

alias jobs="jobs -l"

# yadm
alias yl="yadm list -a"

alias bathelp='bat --plain --language=help'
help() {
    "$@" --help 2>&1 | bathelp
}

#============= ALIASES
# ls
# -Gg = long listing like -l, but without group and owner
# -h = human-readable size
# -p = add / to directories
#alias ls='ls -Gghp --time-style=long-iso --color=auto --group-directories-first'
#alias lsa='ls -Gghpa --time-style=long-iso --color=auto --group-directories-first'
alias ls='exa -lh --group-directories-first'
alias lsa='exa -lha --group-directories-first'
alias cat='bat'
alias cl='clear'
alias yd="yt-dlp -S 'ext,res:1080,br,codec' --embed-metadata "
alias rm='rm -rf'
alias npm='npm --no-fund'

edit() {
  [ -f "$1" ] && gnome-text-editor -- "$1" &> /dev/null &
}
