#!/bin/sh

# core-utils
alias rm='rm -rf'
alias npm='npm --no-fund'

# yadm
alias yadml="yadm list -a"
alias yadma="yadm add"
alias yadmu="yadm add -u"
alias yadmp="yadm commit -m "add/update" && yadm push"
alias yadms="yadm status"

# exa (needs nerd-fonts)
alias ls='exa -lhF --group-directories-first --icons -s extension'
alias lsa='exa -lhFa --group-directories-first --icons -s extension'

# bat
alias cat='bat'
# use help [program] instead of [program] --help (this will colorize it)
help() {
  "$@" --help 2>&1 | bat --plain --language=help
}

# yt-dlp
alias yd="yt-dlp -S 'ext,res:1080,br,codec' --embed-metadata "

# gnome DE
edit() {
  [ -f "$1" ] && gnome-text-editor -- "$1" &> /dev/null &
}
