onboarding = false

[keys]
prefix = "ctrl+e"
new_workspace = "prefix+n"
rename_workspace = "prefix+shift+n"
close_workspace = "prefix+shift+x"
close_tab = "prefix+shift+d"
new_tab = "prefix+c"
rename_tab = "prefix+shift+c"
split_vertical = "prefix+|"
split_horizontal = "prefix+-"
close_pane = "prefix+x"
fullscreen = "prefix+f"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"
reload_config = "prefix+shift+r"
previous_workspace = "alt+shift+["
next_workspace = "alt+shift+]"
previous_tab = "alt+["
next_tab = "alt+]"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"
edit_scrollback = "prefix+e"

[ui]
prompt_new_tab_name = false
sidebar_width = 20
mouse_capture = true
confirm_close = true
show_agent_labels_on_pane_borders = true
agent_panel_scope = "all"

[ui.toast]
delivery = "system"

[ui.sound]
enabled = true

[ui.sound.agents]
claude = "default"
pi = "default"

[theme]
name = "gruvbox"

[experimental]
kitty_graphics = true

[advanced]
scrollback_limit_bytes = 10000000
