onboarding = false

[keys]
prefix = "ctrl+e"
new_workspace = "super+n"
rename_workspace = "super+shift+r"
close_workspace = "super+x"
close_tab = "super+shift+w"
new_tab = "super+t"
rename_tab = "super+r"
split_vertical = "prefix+|"
split_horizontal = "prefix+-"
close_pane = "super+w"
fullscreen = "prefix+f"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"
reload_config = "prefix+shift+r"
previous_workspace = "super+shift+["
next_workspace = "super+shift+]"
previous_tab = "super+["
next_tab = "super+]"
previous_agent = "alt+["
next_agent = "alt+]"
switch_workspace = "alt+shift+1..9"
switch_tab = "alt+1..9"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"
edit_scrollback = "prefix+e"

[ui]
prompt_new_tab_name = false
sidebar_width = 20
mouse_capture = true
confirm_close = true
show_agent_labels_on_pane_borders = true
agent_panel_scope = "all"

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = true

[ui.sound.agents]
claude = "default"
pi = "default"

[theme]
name = "terminal"

[session]
resume_agents_on_restore = true

[experimental]
kitty_graphics = true
pane_history = true

[advanced]
scrollback_limit_bytes = 10000000
