[general]
import = [
    "~/.config/alacritty/base16-irblack.toml", # https://github.com/aarowill/base16-alacritty/blob/c95c200b3af739708455a03b5d185d3d2d263c6e/colors/base16-irblack-256.toml
    "~/.config/alacritty/keybindings.toml",
]

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 13

[window]
opacity = 0.80
blur = true
padding = { x = 2, y = 0 }
option_as_alt = "Both"
startup_mode = "SimpleFullscreen"
decorations = "none"
