# browse base16 themes: https://glitchbone.github.io/vscode-base16-term/#/irblack
import = [
	# source https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-irblack-256.toml
	"~/.config/alacritty/base16-irblack-256.toml",
]

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }

[window]
decorations = "None"
opacity = 0.9
