# browse base16 themes: https://glitchbone.github.io/vscode-base16-term/#/irblack
import = [
	# source https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-irblack-256.toml
	"~/.config/alacritty/base16-irblack.toml",
]

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 12

[window]
opacity = 0.8
padding = { x = 5, y = 5 }
blur = true
option_as_alt = "Both"
