[keyboard]
bindings = [
    { key = "T", mods = "Command", action = "ReceiveChar" },
    { key = "]", mods = "Command|Shift", action = "ReceiveChar" },
    { key = "[", mods = "Command|Shift", action = "ReceiveChar" },
    { key = "Tab", mods = "Command", action = "ReceiveChar" },
    { key = "Tab", mods = "Command|Shift", action = "ReceiveChar" },
    { key = "1", mods = "Command", action = "ReceiveChar" },
    { key = "2", mods = "Command", action = "ReceiveChar" },
    { key = "3", mods = "Command", action = "ReceiveChar" },
    { key = "4", mods = "Command", action = "ReceiveChar" },
    { key = "5", mods = "Command", action = "ReceiveChar" },
    { key = "6", mods = "Command", action = "ReceiveChar" },
    { key = "7", mods = "Command", action = "ReceiveChar" },
    { key = "8", mods = "Command", action = "ReceiveChar" },
    { key = "9", mods = "Command", action = "ReceiveChar" },
]
