#!/usr/bin/env bun

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface Palette {
  source: string;
  hue: number;
  accent: string;
  background: string;
}

const foreground = "#e4e4ef";
const danger = "#ff7b7b";
const warning = "#eed49f";
const accentTemplate = "hsl(0, 18%, 68%)";
const backgroundTemplate = "hsl(0, 12%, 24.1%)";

function run(command: string, args: string[], options: { quiet?: boolean } = {}) {
  try {
    return execFileSync(command, args, {
      encoding: "utf8",
      stdio: options.quiet ? ["ignore", "pipe", "pipe"] : ["inherit", "pipe", "inherit"],
    }).trim();
  } catch (error) {
    throw new Error(`Command failed: ${command} ${args.join(" ")}`);
  }
}

function optionalRun(command: string, args: string[]) {
  try {
    execFileSync(command, args, { stdio: "ignore" });
  } catch {
    // Optional live reload failed. The source files were still updated.
  }
}

function hexToArgb(hex: string, alpha: string) {
  return `0x${alpha}${hex.replace("#", "")}`.toLowerCase();
}

function normalizeColor(input: string) {
  return run("pastel", ["format", "hex", input], { quiet: true }).toLowerCase();
}

function colorFromPicker() {
  return run("pastel", ["format", "hex", "pick"], { quiet: true }).toLowerCase();
}

function derivePalette(source: string): Palette {
  const normalizedSource = normalizeColor(source);
  const hue = Number(run("pastel", ["format", "hsl-hue", normalizedSource], { quiet: true }));

  if (!Number.isFinite(hue)) {
    throw new Error(`Could not derive hue from ${normalizedSource}`);
  }

  const accent = normalizeColor(run("pastel", ["set", "hsl-hue", String(hue), accentTemplate], { quiet: true }));
  const background = normalizeColor(run("pastel", ["set", "hsl-hue", String(hue), backgroundTemplate], { quiet: true }));

  return {
    source: normalizedSource,
    hue,
    accent,
    background,
  };
}

function renderPaletteJson(palette: Palette) {
  return `${JSON.stringify(palette, null, 2)}\n`;
}

function renderPaletteShell(palette: Palette) {
  return `# Generated by ~/.config/theme/apply-theme.ts. Do not edit by hand.

export TRANSPARENT=0x00000000

export ACCENT=${hexToArgb(palette.accent, "ff")}
export BACKGROUND=${hexToArgb(palette.background, "d4")}

export FOREGROUND=${hexToArgb(foreground, "ff")}
export DANGER=${hexToArgb(danger, "ff")}
export WARNING=${hexToArgb(warning, "ff")}

export BORDER_ACTIVE=${hexToArgb(palette.accent, "ff")}
export BORDER_INACTIVE=${hexToArgb(palette.background, "ff")}
`;
}

function sourceRoot() {
  return run("chezmoi", ["source-path"], { quiet: true });
}

function themeDir() {
  return join(sourceRoot(), "dot_config", "theme");
}

function isPalette(value: unknown): value is Palette {
  if (!value || typeof value !== "object") {
    return false;
  }

  const candidate = value as Record<string, unknown>;

  return (
    typeof candidate.source === "string" &&
    typeof candidate.hue === "number" &&
    typeof candidate.accent === "string" &&
    typeof candidate.background === "string"
  );
}

function readPalette(path: string) {
  const parsed: unknown = JSON.parse(readFileSync(path, "utf8"));

  if (!isPalette(parsed)) {
    throw new Error(`Invalid palette file: ${path}`);
  }

  return parsed;
}

function writePaletteFiles(palette: Palette) {
  const dir = themeDir();

  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "palette.json"), renderPaletteJson(palette));
  writeFileSync(join(dir, "palette.sh"), renderPaletteShell(palette));
}

function writePalette(palette: Palette) {
  const dir = themeDir();
  const currentPath = join(dir, "palette.json");

  if (existsSync(currentPath)) {
    const current = readPalette(currentPath);
    writeFileSync(join(dir, "palette.previous.json"), renderPaletteJson(current));
  }

  writePaletteFiles(palette);
}

function undoPalette() {
  const dir = themeDir();
  const currentPath = join(dir, "palette.json");
  const previousPath = join(dir, "palette.previous.json");

  if (!existsSync(previousPath)) {
    throw new Error("No previous palette to restore");
  }

  const previous = readPalette(previousPath);

  if (existsSync(currentPath)) {
    const current = readPalette(currentPath);
    writeFileSync(previousPath, renderPaletteJson(current));
  }

  writePaletteFiles(previous);
  return previous;
}

function applyTheme() {
  const home = process.env.HOME;

  if (!home) {
    throw new Error("HOME is not set");
  }

  run("chezmoi", [
    "apply",
    join(home, ".config", "theme"),
    join(home, ".config", "sketchybar"),
    join(home, ".config", "borders"),
  ]);
  optionalRun("sketchybar", ["--reload"]);
  optionalRun(join(home, ".config", "borders", "bordersrc"), []);
}

function main() {
  if (process.argv.includes("--undo")) {
    const palette = undoPalette();

    applyTheme();

    console.log(`Restored theme from ${palette.source} at hue ${palette.hue}`);
    console.log(`accent ${palette.accent} / background ${palette.background}`);
    return;
  }

  const input = process.argv[2]?.trim() || colorFromPicker();
  const palette = derivePalette(input);

  writePalette(palette);
  applyTheme();

  console.log(`Applied theme from ${palette.source} at hue ${palette.hue}`);
  console.log(`accent ${palette.accent} / background ${palette.background}`);
}

main();
