# Strip the gibo attribution header from generated .gitignore boilerplates.
export def --wrapped "gibo-strip" [...boilerplates: string] {
  mut out = []
  mut skip = 0

  for line in (^gibo dump ...$boilerplates | lines) {
    if $skip > 0 {
      $skip = ($skip - 1)
    } else if ($line | str starts-with '### Generated by gibo') {
      $skip = 2
    } else {
      $out = ($out | append $line)
    }
  }

  $out | str join (char nl)
}
