theme = "gruber-darker-local"

[keys.insert]
 j = { j = "normal_mode" }

[keys.normal]
C-j = [ "keep_primary_selection", "move_line_down", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection", "move_line_down" ]
C-k = [ "keep_primary_selection", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection" ]
esc = ["collapse_selection", "keep_primary_selection"]
A-j = "scroll_down"
A-k = "scroll_up"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor]
true-color = true
mouse = false
middle-click-paste =  false
line-number = "relative"
bufferline = "multiple"
rulers = [80]

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
