theme = "gruber-darker-local"


# https://docs.helix-editor.com/keymap.html or space+?

[keys.normal]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal.space]
P = "no_op"
p = ":format"
o = ":write"
x = ":buffer-close"
q = ":quit"
"`" = [":config-reload", ":lsp-restart"]
e = [":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- nu ~/.config/helix/yazi-picker.nu"]
i = [":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -c -- lazygit"]

[keys.insert]
C-h = "move_char_left"
C-l = "move_char_right"
C-space = "completion"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.insert.j]
j = "normal_mode"

[keys.select]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]


# https://docs.helix-editor.com/configuration.html

[editor]
shell = ["nu", "-c"]
line-number = "relative"
bufferline = "multiple"
rulers = [80]
# color-modes = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-absolute-path", "read-only-indicator", "file-modification-indicator"]
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"

[editor.soft-wrap]
enable = true

# [editor.lsp]
# display-messages = true
