# docs: https://docs.helix-editor.com/configuration.html

theme = "gruber-darker-local"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-j = "scroll_down"
A-k = "scroll_up"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal.g]
"[" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80]
color-modes = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
