# docs: https://docs.helix-editor.com/configuration.html

theme = "gruber-darker-local"

[keys.insert]
j = { j = "normal_mode" }

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
H = ":buffer-previous"
L = ":buffer-next"
A-j = "scroll_down"
A-k = "scroll_up"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# file picker using yazi (workaround until helix plugin is implemented)
[keys.normal."space"]
e = [":sh zellij run --floating -x 10% -y 10% --width 80% --height 80% -- nu ~/.config/nushell/scripts/yazi-picker.nu"]
"[" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80]
color-modes = true
# soft-wrap.enable = true
# soft-wrap.max-indent-retain = 80

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
