# docs: https://docs.helix-editor.com/languages.html
# default: https://github.com/helix-editor/helix/blob/master/languages.toml

# WARN there is plan to replace the language from toml to "scheme" idk wtf that is
# https://github.com/helix-editor/helix/issues/10389
# https://github.com/helix-editor/helix/issues/8853

[[language]]
name = "toml"
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "taplo", args = ["fmt", "-o", "indent_string=\t", "-o", "inline_table_expand=false", "-o", "column_width=120", "-"] }

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "kdl"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "nu"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = 'shfmt', args = ["-i", "0"] } # 0 for tabs, 1..4 for N of spaces

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--config-precedence", "file-override", "--no-semi", "--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--config-precedence", "file-override", "--no-semi", "--parser", "typescript"] }

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--config-precedence", "file-override", "--no-semi", "--parser", "typescript"] }
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--config-precedence", "file-override", "--no-semi", "--parser", "typescript"] }
language-servers = ["typescript-language-server", "tailwindcss-ls"]
